### ISSUE TITLE
[Prose]: Navigation Issues

### ISSUE THREAD

**Issue by IanHakes-okta** [okta/okta-developer-docs#951] opened 2020-02-14 19:35 UTC
Issue 1)
From "Docs" header in the navigation tree, the landing pages all give different results:
Docs > Concepts => landing page with new LHN, shows all concept topics
Docs > Guides => landing page, LHN different (broken) style, shows all guide topics
Docs > Reference => landing page, but no LHN, does not cover all the reference items available

Issue 2)
Reference section - click on Open ID Connect & OAuth2.0
<img width="315" alt="Screen Shot 2020-02-14 at 11 12 01 AM" src="https://user-images.githubusercontent.com/54096608/74562067-d33fac00-4f1e-11ea-97ff-c36e77cb6e73.png">

Click on Manage Okta Resources (to expand item).
<img width="302" alt="Screen Shot 2020-02-14 at 11 17 46 AM" src="https://user-images.githubusercontent.com/54096608/74562098-e2265e80-4f1e-11ea-9b6c-84a739b9f07b.png">
OpenID Connect and OAuth 2.0 API menu item gets resized

Issue 3) 
Cannot resize left hand nav area.

Issue 4)
Concepts, Guides, Reference areas all have different looking LHN
<img width="275" alt="Screen Shot 2020-02-14 at 11 19 02 AM" src="https://user-images.githubusercontent.com/54096608/74562180-17cb4780-4f1f-11ea-8708-d2d259a9be25.png">
<img width="258" alt="Pasted Graphic 6" src="https://user-images.githubusercontent.com/54096608/74562241-421d0500-4f1f-11ea-8193-da63610fe5ff.png">
<img width="256" alt="Pasted Graphic 7" src="https://user-images.githubusercontent.com/54096608/74562252-46492280-4f1f-11ea-95d5-8e2e1617f0ec.png">

￼Reference LHN should be titled "Reference" (no "s") and shouldn't be clickable.

**Comment by bretterer** [comment] 2020-02-14 19:51
> Issue 1)
> From "Docs" header in the navigation tree, the landing pages all give different results:
> Docs > Concepts => landing page with new LHN, shows all concept topics
> Docs > Guides => landing page, LHN different (broken) style, shows all guide topics
> Docs > Reference => landing page, but no LHN, does not cover all the reference items available

Guides was not part of this migration, so it will look different.  Not sure what you mean by "does not cover all the reference items"

> 
> Issue 2)
> Reference section - click on Open ID Connect & OAuth2.0
> 
> Click on Manage Okta Resources (to expand item).
> OpenID Connect and OAuth 2.0 API menu item gets resized

This is working as expected.  The "resize" is because when the resources are open, the LHN is scrollable, so the scrollbar squishes items.

> 
> Issue 3)
> Cannot resize left hand nav area.

In what way?   there is not resize capability in general for LHN

> 
> Issue 4)
> Concepts, Guides, Reference areas all have different looking LHN
> 
> ￼Reference LHN should be titled "Reference" (no "s") and shouldn't be clickable.

Thanks. The guides section is Out of Scope for this. The concepts have a landing page which is why it appears to have a sidebar link.  The `reference` is not clickable, but has a hand, so I will make a note to remove that.

**Comment by alexdahl-okta** [comment] 2020-02-19 01:46
I can't reproduce `#2`, but it shouldn't occur. The tree nav should have a fixed width and items inside it should not reflow.

On `#4`, the Reference, Concepts, and Languages & SDKs sections should all work the same way. (Guides should eventually as well.) The first item in the tree nav for each section should be the link to the section's overview page. The section overview pages are just articles, and should use the same prose layout.

**Comment by dogeared** [comment] 2021-01-12 17:23
moved to: https://oktainc.atlassian.net/browse/OKTA-360200

**Closed by dogeared** 2021-01-12 17:23 UTC
Labels: Prose Theme, ui
