### ISSUE TITLE
Additional documentation regarding API rate limits

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-developer-docs#4443] opened 2023-10-23 14:33 UTC
Thank you for getting involved with Okta's Developer Docs!

> Note: If you are an Okta employee, please [clone this Jira](https://oktainc.atlassian.net/browse/OKTA-250417) instead of opening a GitHub issue.

Please provide the following information so that we can act on your feedback.

**Affected page(s):**
https://github.com/okta/okta-developer-docs/edit/master/packages/@okta/vuepress-site/docs/reference/rl-best-practices/index.md

**Describe the problem(s):**
It would be great if these pages would mention the option to increase the `limit` parameter beyond its default of `200` to its max (which varies per endpoint)
Currently the max value for each endpoint is not well documented, it'd be great if this ended up in the Open API spec v2 and/or v3

There is also limited information on what to do when you feel the Okta API rate limit default values are inappropriate (to low compared to other values, to low given instance scale)
its also difficult for Okta Admins not involved in procurement to determine if dynamic scale has been purchased for their org, or if they got a multiplier due to instance size, some documentation in this space would be amazing

**If possible, describe a proposed fix:**

We will do our best to respond to you within 2 working days.

**Comment by brianduffield-okta** [comment] 2023-10-25 20:10
Thanks for opening the issue, @exitcode0. I'll work with engineering to review your request and update the docs. I'll keep the issue updated on my progress.

**Comment by brianduffield-okta** [comment] 2023-11-02 20:20
Hi @exitcode0 

Regarding your first question, can you provide more details on a specific `limit` parameter? I don't see this with any of the Rate Limit APIs. If your endpoints are not showing the full max, it could be due to the API Token settings, which, by default, are set to 50% of the endpoint's maximum, see: [https://developer.okta.com/docs/reference/rate-limits/#api-rate-limits-by-token](https://developer.okta.com/docs/reference/rate-limits/#api-rate-limits-by-token)

We are in the process of improving the documentation for the max value of each endpoint, and I've taken your suggestion to the Open API spec team, which is currently reviewing adding this content. For now, the best location to view individual endpoint rate limits is in the APIs table of the rate limit dashboard: [https://developer.okta.com/docs/reference/rl-dashboard/#apis-table](https://developer.okta.com/docs/reference/rl-dashboard/#apis-table.)

You can also use this table to filter on endpoints that have applied (or eligible) rate limit multipliers, which can help you determine if DynamicScale is purchased (The Rate limit multiplier is an add-on feature: [https://developer.okta.com/docs/reference/rl-dashboard/#rate-limit-multiplier](https://developer.okta.com/docs/reference/rl-dashboard/#rate-limit-multiplier))

As per your comments, I'm looking to improve documentation on how to highlight changing rate limit values if an admin believes they are inappropriate (too low), but fundamentally it would require an update to org type or the purchase of DynamicScale. Hope this helps.

**Comment by brianduffield-okta** [comment] 2023-11-03 15:18
Hi @exitcode0 

Thanks, yes, I understand your reference to the `limit` parameter now, and it would make a good addition to the docs, perhaps in the Best Practices reference. 

The maximum value for the `limit` parameter, in theory, should be documented for applicable endpoints, but as we migrate content to OAS3 we are noticing some gaps. I'll make sure to highlight that for the team.

In terms of improving the documentation for the max value of each endpoint, I was referring to adding the maximum rate limit to the docs, which is something I think we can, and should, do.

I'll check back with PM/engineering on documentation of your questions regarding the buckets. Thanks for the questions!

**Comment by brianduffield-okta** [comment] 2023-11-22 17:12
Hi @exitcode0 

We've recently merged an update to the Rate Limit docs, mainly to the [Rate limit best practices](https://developer.okta.com/docs/reference/rl-best-practices/), where we've added content on the use of the Rate limit dashboard and added a section on api `limit` parameter as you suggested. We've also updated the [Rate limit dashboard](https://developer.okta.com/docs/reference/rl-dashboard/) content to provide some more context around the endpoints that appear in the table and to highlight options to increase limits.

Overall, I've added more links to these pages from the other rate limit docs to highlight contacting support for any configurations or updates. As rate limit configurations vary based on org and use cases, we avoided details on specifics (i.e. buckets).

If these updates are okay, I'll close the issue. But feel free to comment if you'd like more detail/info. Thanks again, for opening the issue.

**Comment by brianduffield-okta** [comment] 2023-11-23 15:22
From our [Management rate limits](https://developer.okta.com/docs/reference/rl-global-mgmt/) documentation, those bulleted endpoints should apply to the `/api/v1/apps/*`, not `/api/v1/users/*` (unless that was a typo). Explicit calls, for example, `/api/v1/apps/${AppId}`, have a separate limit from `/api/v1/apps/*`, which is what I was trying to get across with that blurb you excerpted and the phrase that followed.  It might be better recast as:

"Unless the endpoint is specifically called out in the dashboard, API endpoints that end with an asterisk (for example, `/api/v1/users/*`, generally refer to calls that use that base schema and count towards that call's limit."

Let me know if that accurately addresses your comment. There does seem to be some confusion around this, and I'd like to get it right. Thanks again, and happy Thanksgiving.

**Comment by brianduffield-okta** [comment] 2023-11-28 14:31
@exitcode0 Updated this wording. Confirmed with engineering that calls to `/api/v1/apps/...` will fall under the limit for `/api/v1/apps*` (unless explicitly called out for a separate limit).

**Closed as completed** 2023-11-29 13:34 UTC
